- name: Execute Bash Script on Slave Node
  hosts: 10.0.2.15
  become: yes
  tasks:
    - name: Copy the provisioning script to the Slave node
      copy:
        src: /home/vagrant/provision.sh
        dest: /tmp/provision.sh
        mode: +x

    - name: Execute the provisioning script
      shell: /tmp/provision.sh

    - name: Set up a cron job to check server uptime at 12 am
      cron:
        name: "check-uptime"
        minute: 0
        hour: 0
        job: "uptime > /var/log/uptime.log"
